### ISSUE TITLE
configparser.NoSectionError: No section: 'config'

### ISSUE THREAD

**Issue by XiaoHb233** [dclemon/jdkill_new#2]
这是什么问题，pc端口的cookie吗

**Comment by dclemon** [comment]
看源码，新建一个config.ini文件配置好需要的信息



发自我的iPhone


------------------ Original ------------------
From: XiaoHb ***@***.***&gt;
Date: Sat,May 28,2022 0:12 AM
To: dclemon/jdkill_new ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [dclemon/jdkill_new] configparser.NoSectionError: No section:'config' (Issue #2)





 
这是什么问题，pc端口的cookie吗
