### ISSUE TITLE
报错啥原因啊

### ISSUE THREAD

**Issue by yejinson** [dclemon/jdkill_new#3]
<img src='https://s2.loli.net/2022/06/01/s98YJ4XZrc6BS7v.png' title='quicker_e3e5eed6-3db8-4519-96f3-5f0b3481f4b7.png' />

**Comment by dclemon** [comment]
验证cookie有效性报错，需要网页版cookie，如果ck没错的话也可能是这个接口过期了，修改代码pass掉这段就行

**Comment by yejinson** [comment]
> 验证cookie有效性报错，需要网页版cookie，如果ck没错的话也可能是这个接口过期了，修改代码pass掉这段就行

<img src='https://s2.loli.net/2022/06/03/XeK9pSQnuzvHrdV.png' title='quicker_123812f1-0235-4550-aefe-19fd943a69a0.png' />
大神，帮忙看下这个报错怎么办啊，谢谢。

**Comment by dclemon** [comment]
> > 验证cookie有效性报错，需要网页版cookie，如果ck没错的话也可能是这个接口过期了，修改代码pass掉这段就行
> 
> ![](https://camo.githubusercontent.com/782ba2094a8c34dbe642328f7a6c93736d4ea3cfec6dd1dfc1c4fe2725ab55a7/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30362f30332f58654b397053516e757a76487264562e706e67)
> 
> 大神，帮忙看下这个报错怎么办啊，谢谢。

不回答低级错误，先去了解python的语法再提问

**Comment by yejinson** [comment]
> > > 验证cookie有效性报错，需要网页版cookie，如果ck没错的话也可能是这个接口过期了，修改代码pass掉这段就行
> > 
> > 
> > ![](https://camo.githubusercontent.com/782ba2094a8c34dbe642328f7a6c93736d4ea3cfec6dd1dfc1c4fe2725ab55a7/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30362f30332f58654b397053516e757a76487264562e706e67)
> > 大神，帮忙看下这个报错怎么办啊，谢谢。
> 
> 不回答低级错误，先去了解python的语法再提问

是ck里面没有pin吧，但是填的ck里明明就有啊
